### PR TITLE
add SETF BUFFER-POSITION and incr POS on stream read. (correct buffer-position behaviour)

### PR DESCRIPTION
**Pull request by Chream**
Updated the function buffer-position to correctly return the position even when there is an underlying stream. The old behaviour just ignored the stream.

The new behaviour is correct when having either: just an array, just a stream or both. It has been implemented only for input buffers. Cant really see a use for changing position for output-buffers and I suspect it might be difficult as there are multiple slots for output.

Sorry for not including any tests. I dont know the test framework checkl. Might get to it if you approve the PR first. Something like this should suffice:

```
(let ((buf (make-input-buffer :vector (make-array 2
                                                  :element-type '(unsigned-byte 8)
                                                  :initial-contents '(1 2))
                              :stream (flexi-streams:make-in-memory-input-stream 
                                       (octets-from '(3 4)))))
      (seq (make-octet-vector 2)))
  (assert (= (buffer-position buf) 0))
  (assert (= (file-position (input-buffer-stream buf)) 0))

  (assert (= (fast-read-byte buf) 1))
  (assert (= (buffer-position buf) 1))
  (assert (= (file-position (input-buffer-stream buf)) 0))

  (assert (= (fast-read-byte buf) 2))
  (assert (= (buffer-position buf) 2))
  (assert (= (file-position (input-buffer-stream buf)) 0))

  (assert (= (fast-read-byte buf) 3))
  (assert (= (buffer-position buf) 3))
  (assert (= (file-position (input-buffer-stream buf)) 1))

  (setf (buffer-position buf) 1)
  (assert (= (buffer-position buf) 1))
  (assert (= (file-position (input-buffer-stream buf)) 0))

  (fast-read-sequence seq buf)
  (assert (= (buffer-position buf) 3))
  (assert (= (file-position (input-buffer-stream buf)) 1))

  (setf (buffer-position buf) 1)
  (assert (= (buffer-position buf) 1))
  (assert (= (file-position (input-buffer-stream buf)) 0))

  (setf (buffer-position buf) 3)
  (assert (= (buffer-position buf) 3))
  (assert (= (file-position (input-buffer-stream buf)) 1)))
```

### CODE REVIEW

**Comment by Chream** [comment]
I believe this basically implements fast-seek aef5f60fb9932c49d5b61356a1ef329578658bf0

**Comment by Gnuxie** [comment]
@rpav @Chream is there a reason we can't have this?

**Comment by rpav** [comment]
Err it just entirely fell off my radar along with most CL stuff... do the basic tests still run?  (Should just need to `asdf`-load `fast-io-tests` and/or `asdf:test` or whatnot...) I'm not really set up to check this stuff at the moment.

**Comment by Gnuxie** [comment]
Hi @rpav , that's understandable

I don't think starting the tests from asdf works for this library, I'm not sure why (I don't usually tell asdf about tests). 

Either way, I have ran the tests locally using CheckL and they do look correct (and as an aside I'm not really sure how you're supposed to find out if something has gone wrong (other than catastrophically) using this framework without manually inspecting them)

**Comment by rpav** [comment]
It will more or less complain about things if the results are different than the last time; generally you just write a thing, eval it for the result, and if that's good, it's a test.  This was generally how I worked in CL anyway, so making something to just automate "check again" seemed natural.

In any case if they look fine, cool, will merge.

**Comment by Gnuxie** [comment]
ok, cool

**Pull request merged**
